### ISSUE TITLE
bot crashing when using newAction

### ISSUE THREAD

**Issue by kortgrabb** [kolbytn/mindcraft#102]
file:///C:/Users/JohnDoe/Desktop/mindcraft-main/src/agent/coder.js:141
            }, settings.code_timeout_mins);
               ^

ReferenceError: settings is not defined
    at Coder.generateCodeLoop (file:///C:/Users/JohnDoe/Desktop/mindcraft-main/src/agent/coder.js:141:16)
    at async Coder.generateCode (file:///C:/Users/JohnDoe/Desktop/mindcraft-main/src/agent/coder.js:86:19)
    at async Object.perform (file:///C:/Users/JohnDoe/Desktop/mindcraft-main/src/agent/commands/actions.js:29:20)
    at async executeCommand (file:///C:/Users/JohnDoe/Desktop/mindcraft-main/src/agent/commands/index.js:89:20)
    at async Agent.handleMessage (file:///C:/Users/JohnDoe/Desktop/mindcraft-main/src/agent/agent.js:125:35)

**Comment by MaxRobinsonTheGreat** [comment]
should now be fixed with #101
