### ISSUE TITLE
Syntax error when running `npm install`

### ISSUE THREAD

**Issue by merll002** [kolbytn/mindcraft#119]
When cloning the latest version of the repo and running `npm install` this error is produced:

```
> postinstall
> patch-package

/home/*/mindcraft/node_modules/yaml/dist/compose/composer.js:33
                if (prelude[i + 1]?.[0] !== '#')
                                   ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:85:18)
    at Object.<anonymous> (/home/*/mindcraft/node_modules/yaml/dist/index.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
npm ERR! code 1
npm ERR! path /home/*/mindcraft
npm ERR! command failed
npm ERR! command sh -c patch-package
```

**Comment by swiftimundo** [comment]
I had this issue as well. Need a newer node version. I followed this guide to get v16.20.2 and that seemed to work. https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-ubuntu-20-04
