### ISSUE TITLE
Issue with Ollama.

### ISSUE THREAD

**Issue by Eatdonut1** [kolbytn/mindcraft#123]
So i have followed everything i was told and i got this error. Could anybody help with this thanks.
C:\Users\Sami\Desktop\mindcraft-main>node main.js
Using chat settings: { model: 'llama3', api: 'ollama' }
Using embedding settings: { api: 'none' }
Unknown embedding:  none . Using word overlap.
Loading examples...
Examples loaded.
Logging in...
C:\Users\Sami\Desktop\mindcraft-main\node_modules\mineflayer\lib\loader.js:108
    const version = require('minecraft-data')(bot._client.version).version
                                                                                              ^

TypeError: Cannot read properties of null (reading 'version')
    at next (C:\Users\Sami\Desktop\mindcraft-main\node_modules\mineflayer\lib\loader.js:108:67)
    at createBot (C:\Users\Sami\Desktop\mindcraft-main\node_modules\mineflayer\lib\loader.js:105:34)
    at initBot (file:///C:/Users/Sami/Desktop/mindcraft-main/src/utils/mcdata.js:52:15)
    at Agent.start (file:///C:/Users/Sami/Desktop/mindcraft-main/src/agent/agent.js:24:20)

Node.js v20.15.1
Agent process exited with code 1 and signal null
Agent process exited too quickly. Killing entire process. Goodbye.

**Comment by saladnoob** [comment]
did you fix this? I had the same problem
