### ISSUE TITLE
Error reading gemini's memory file

### ISSUE THREAD

**Issue by starwar12** [kolbytn/mindcraft#133]
I keep getting this error

gemini spawned.
selected examples:
miner_32: Hey! What are you up to?
grombo_Xx: What do you see?
Awaiting Google API response...
node:internal/process/promises:391
    triggerUncaughtException(err, true /* fromPromise */);
    ^

GoogleGenerativeAIError: [400 Bad Request] Gemini API free tier is not available in your country. Please enable billing on your project in Google AI Studio.
    at makeRequest (file:///C:/mindcraft-main/node_modules/@google/generative-ai/dist/index.mjs:210:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async generateContent (file:///C:/mindcraft-main/node_modules/@google/generative-ai/dist/index.mjs:534:22)
    at async Gemini.sendRequest (file:///C:/mindcraft-main/src/models/gemini.js:29:24)
    at async Prompter.promptConvo (file:///C:/mindcraft-main/src/agent/prompter.js:158:16)
    at async Agent.handleMessage (file:///C:/mindcraft-main/src/agent/agent.js:104:23)

Node.js v20.16.0
Agent process exited with code 1 and signal null
Restarting agent...
Using chat settings: { model: 'gemini-1.5-pro', api: 'google' }
Using embedding settings: { api: 'google' }
Loading examples...
Examples loaded.
Logging in...
Error reading gemini's memory file: ENOENT: no such file or directory, open 'C:\mindcraft-main\bots\gemini\memory.json'
Mineflayer detected that you are using a deprecated event (physicTick)! Please use this event (physicsTick) instead.

**Comment by EIegance** [comment]
The issue is directly in the first line. `Gemini API free tier is not available in your country. Please enable billing on your project in Google AI Studio.`

You need to pay for the use of the API
