### ISSUE TITLE
help bro i dont know happens

### ISSUE THREAD

**Issue by Dungsenpart** [kolbytn/mindcraft#153]
file:///C:/Users/PC/Downloads/mindcraft-main/node_modules/@google/generative-ai/dist/index.mjs:265
                throw new GoogleGenerativeAIResponseError(`${formatBlockErrorMessage(response)}`, response);
                      ^

GoogleGenerativeAIResponseError: [GoogleGenerativeAI Error]: Candidate was blocked due to RECITATION
    at response.text (file:///C:/Users/PC/Downloads/mindcraft-main/node_modules/@google/generative-ai/dist/index.mjs:265:23)
    at Gemini.sendRequest (file:///C:/Users/PC/Downloads/mindcraft-main/src/models/gemini.js:31:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Prompter.promptMemSaving (file:///C:/Users/PC/Downloads/mindcraft-main/src/agent/prompter.js:170:16)
    at async History.storeMemories (file:///C:/Users/PC/Downloads/mindcraft-main/src/agent/history.js:25:23)
    at async History.add (file:///C:/Users/PC/Downloads/mindcraft-main/src/agent/history.js:45:13) {
  response: {
    candidates: [ { finishReason: 'RECITATION', index: 0 } ],
    usageMetadata: { promptTokenCount: 221, totalTokenCount: 221 },
    text: [Function (anonymous)]
  }
}

Node.js v20.16.0
Agent process exited with code 1 and signal null

**Comment by venkatmidhunmareedu** [comment]
see [this](https://github.com/google/generative-ai-docs/issues/257)

Its a know issue and their is no proper solution for it. 

What to do: 

Use another provider (Groq (recommended)) or Ollama (if you have a big GPU 🔥 and CPU)

**Comment by pixelkat5** [comment]
I never really understood how you use ollama models with Mindcraft...

> see [this](https://github.com/google/generative-ai-docs/issues/257)
> 
> Its a know issue and their is no proper solution for it.
> 
> What to do:
> 
> Use another provider (Groq (recommended)) or Ollama (if you have a big GPU 🔥 and CPU)

**Comment by venkatmidhunmareedu** [comment]
See [this](https://github.com/kolbytn/mindcraft/issues/426#issuecomment-2627331212)

**Comment by uukelele** [comment]
https://github.com/google/generative-ai-docs/issues/257 has been closed.
