### ISSUE TITLE
Meta llama3.1 cant run

### ISSUE THREAD

**Issue by saladnoob** [kolbytn/mindcraft#156]
I tried to run main.js but the path is wrong

Error: ENOENT: no such file or directory, open 'D:\mindcraft-main\llama.json'
    at readFileSync (node:fs:448:20)
    at new Prompter (file:///D:/mindcraft-main/src/agent/prompter.js:18:35)
    at Agent.start (file:///D:/mindcraft-main/src/agent/agent.js:15:25)
    at file:///D:/mindcraft-main/src/process/init-agent.js:27:13
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:123:5) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'D:\\mindcraft-main\\llama.json'
}

here's the js file

settings.js:

export default 
{
    "minecraft_version": "1.20.1", // supports up to 1.20.4
    "host": "192.168.0.39", // or "localhost", "your.ip.address.here"
    "port": 55916,
    "auth": "offline", // or "microsoft"
    
    "profiles": [
        "./llama.json",
        // add more profiles here, check ./profiles/ for more
        // more than 1 profile will require you to /msg each bot indivually
    ],
    "load_memory": false, // load memory from previous session
    "init_message": "Say hello world and your name", // sends to all on spawn

    "allow_insecure_coding": false, // allows newAction command and model can write/run code on your computer. enable at own risk
    "code_timeout_mins": 10, // minutes code is allowed to run. -1 for no timeout
    
    "max_commands": -1, // max number of commands to use in a response. -1 for no limit
    "verbose_commands": true, // show full command syntax
    "narrate_behavior": true, // chat simple automatic actions ('Picking up item!')
}

when doing anything related to ollama llama3.1 i only did these to the terminal

ollama pull llama3; ollama pull nomic-embed-text
npm install

what should i do?
![image](https://github.com/user-attachments/assets/1af295e7-fc05-478a-9cec-2757f3cd1b96)

**Comment by saladnoob** [comment]
I have fixed the issue

this part of the settings.js

    "profiles": [
        "./andy.json",

i replaced it with "llama.json" cus i thought it would use the llama.json under profile.
