### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Etham5** [kolbytn/mindcraft#164]
Agent process exited with code 1 and signal null
Agent process exited too quickly. Killing entire process. Goodbye.
PS C:\Users\ethan\Downloads\mindcraft-main> node main.js
undefined:21
    },
    ^

SyntaxError: Expected double-quoted property name in JSON at position 3027
    at JSON.parse (<anonymous>)
    at new Prompter (file:///C:/Users/ethan/Downloads/mindcraft-main/src/agent/prompter.js:18:29)
    at Agent.start (file:///C:/Users/ethan/Downloads/mindcraft-main/src/agent/agent.js:15:25)
    at file:///C:/Users/ethan/Downloads/mindcraft-main/src/process/init-agent.js:27:13
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:123:5)

Node.js v20.15.0
Agent process exited with code 1 and signal null
Agent process exited too quickly. Killing entire process. Goodbye.

**Comment by FantomWolf182** [comment]
Replace prompter.js with a new copy from this repo.

**Comment by uukelele** [comment]
Fix JSON errors in your profile files.
