### ISSUE TITLE
llama3

### ISSUE THREAD

**Issue by mrrat1337** [kolbytn/mindcraft#170]
C:\Users\razvan\Downloads\mindcraft-main\mindcraft-main>node main.js
file:///C:/Users/razvan/Downloads/mindcraft-main/mindcraft-main/settings.js:8
    "profiles": [
    ^^^^^^^^^^

SyntaxError: Unexpected string
    at compileSourceTextModule (node:internal/modules/esm/utils:339:16)
    at ModuleLoader.moduleStrategy (node:internal/modules/esm/translators:168:18)
    at callTranslator (node:internal/modules/esm/loader:428:14)
    at ModuleLoader.moduleProvider (node:internal/modules/esm/loader:434:30)

Node.js v20.17.0

**Comment by mrrat1337** [comment]
C:\Users\razvan\Downloads\mindcraft-main\mindcraft-main>node main.js
keys.json not found. Defaulting to environment variables.
node:fs:448
    return binding.readFileUtf8(path, stringToFlags(options.flag));
                   ^

Error: ENOENT: no such file or directory, open 'C:\Users\razvan\Downloads\mindcraft-main\mindcraft-main\llama.json'
    at readFileSync (node:fs:448:20)
    at new Prompter (file:///C:/Users/razvan/Downloads/mindcraft-main/mindcraft-main/src/agent/prompter.js:18:35)
    at Agent.start (file:///C:/Users/razvan/Downloads/mindcraft-main/mindcraft-main/src/agent/agent.js:15:25)
    at file:///C:/Users/razvan/Downloads/mindcraft-main/mindcraft-main/src/process/init-agent.js:27:13
    at ModuleJob.run (node:internal/modules/esm/module_job:234:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:473:24)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:123:5) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\razvan\\Downloads\\mindcraft-main\\mindcraft-main\\llama.json'
}

Node.js v20.17.0
Agent process exited with code 1 and signal null
Agent process exited too quickly. Killing entire process. Goodbye.

**Comment by IDKMANPLAYZ** [comment]
Did you change keys.example.json and removed .example from it and add your keys

**Comment by mrrat1337** [comment]
yes

**Comment by mrrat1337** [comment]
![image](https://github.com/user-attachments/assets/1875a409-ec38-4f65-a3d3-c32876feb884)
![image](https://github.com/user-attachments/assets/04f9f458-ab14-4b99-99ff-a5cc13931c5d)

**Comment by mrrat1337** [comment]
![image](https://github.com/user-attachments/assets/32965d9b-cabf-4301-ab65-fded5dd84dd4)

**Comment by uukelele** [comment]
Make sure you have no mods installed and use node.js 22 (LTS). If the issue persists, reopen the issue.
