### ISSUE TITLE
RateLimitError: 429

### ISSUE THREAD

**Issue by Rishi12309** [kolbytn/mindcraft#173]
PS C:\Users\pc\Documents\Minecraft\mindcraft-main> node main.js
Using chat settings: { model: 'gpt-4o-mini', api: 'openai' }
Using embedding settings: { api: 'openai' }
file:///C:/Users/pc/Documents/Minecraft/mindcraft-main/node_modules/openai/error.mjs:59
            return new RateLimitError(status, error, message, headers);
                   ^

RateLimitError: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.
    at APIError.generate (file:///C:/Users/pc/Documents/Minecraft/mindcraft-main/node_modules/openai/error.mjs:59:20)
    at OpenAI.makeStatusError (file:///C:/Users/pc/Documents/Minecraft/mindcraft-main/node_modules/openai/core.mjs:268:25)
    at OpenAI.makeRequest (file:///C:/Users/pc/Documents/Minecraft/mindcraft-main/node_modules/openai/core.mjs:311:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async GPT.embed (file:///C:/Users/pc/Documents/Minecraft/mindcraft-main/src/models/gpt.js:51:27)
    at async file:///C:/Users/pc/Documents/Minecraft/mindcraft-main/src/utils/examples.js:37:46
    at async Promise.all (index 14)
    at async Examples.load (file:///C:/Users/pc/Documents/Minecraft/mindcraft-main/src/utils/examples.js:39:13)
    at async Promise.all (index 0)
    at async Prompter.initExamples (file:///C:/Users/pc/Documents/Minecraft/mindcraft-main/src/agent/prompter.js:101:9) {
  status: 429,
  headers: {
    'alt-svc': 'h3=":443"; ma=86400',
    'cf-cache-status': 'DYNAMIC',
    'cf-ray': '8bbe0953f9d97ea0-MAA',
    connection: 'keep-alive',
    'content-length': '337',
    'content-type': 'application/json; charset=utf-8',
    date: 'Sat, 31 Aug 2024 15:26:00 GMT',
    server: 'cloudflare',
    'set-cookie': '__cf_bm=8MUY60VsHwSmGNe7UUi9uX8g9nGmPrv.yJUuacswHpg-1725117960-1.0.1.1-hAMFHYxl7eCjpTPpB3xIhH4JcDV5B1AMBz1VmA5b0f8axJFjhOUi.DiuMvXio9q9u4clvX2ez1ep_eYhAloH3A; path=/; expires=Sat, 31-Aug-24 15:56:00 GMT; domain=.api.openai.com; HttpOnly; Secure; SameSite=None, _cfuvid=5TWjNQHUpQc2IbxOx2.9R1nYBkxYYXVujniJvMXytwU-1725117960602-0.0.1.1-604800000; path=/; domain=.api.openai.com; HttpOnly; Secure; SameSite=None',
    'strict-transport-security': 'max-age=15552000; includeSubDomains; preload',
    vary: 'Origin',
    'x-content-type-options': 'nosniff',
    'x-request-id': 'req_c6f0549605b3de303caab6293cbccf50'
  },
  request_id: 'req_c6f0549605b3de303caab6293cbccf50',
  error: {
    message: 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.',
    type: 'insufficient_quota',
    param: null,
    code: 'insufficient_quota'
  },
  code: 'insufficient_quota',
  param: null,
  type: 'insufficient_quota'
}

Node.js v18.20.4
Agent process exited with code 1 and signal null
Agent process exited too quickly. Killing entire process. Goodbye.

**Comment by mrrat1337** [comment]
you don t have balance on  open ai.
