### ISSUE TITLE
Can't figure out how to use my existing LM Studio installation: Cannot read properties of undefined (reading 'content'), brain disconnected.

### ISSUE THREAD

**Issue by Gyramuur** [kolbytn/mindcraft#180]
Since I've already got Llama 3 set up locally in LM Studio, I figured I would be able to use that program since it allows you to host a local server to "mimic OpenAI endpoints".

Anyway, I've gotten most of the way there. Since it's running locally, I shouldn't need an API key and the keys.json isn't touched.

In andy.json and andy_npc.json I changed "model" to "llama3".

I also edited the Local class of src/models/local.js to use the endpoints from LM Studio, and that looks like this:

```
export class Local {
    constructor(model_name, url) {
        this.model_name = model_name;
        this.url = url || 'http://localhost:1234';
        this.chat_endpoint = '/v1/chat';
        this.embedding_endpoint = '/v1/embeddings';
```
        
        
This almost works, and the bot joins my server, but upon running "node main.js" I get a TypeError:

```
keys.json not found. Defaulting to environment variables.
Using chat settings: { model: 'llama3', api: 'ollama' }
Using embedding settings: { api: 'none' }
Unknown embedding:  none . Using word overlap.
Logging in...
Mineflayer detected that you are using a deprecated event (physicTick)! Please use this event (physicsTick) instead.
andy spawned.
selected examples:
brug: Remember that your base is here.
user43: Set a goal to survive on your own forever.
Awaiting local response... (model: llama3)
TypeError: Cannot read properties of undefined (reading 'content')
    at Local.sendRequest (file:///Z:/llm/mindcraft-main/src/models/local.js:20:37)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Prompter.promptConvo (file:///Z:/llm/mindcraft-main/src/agent/prompter.js:165:16)
    at async Agent.handleMessage (file:///Z:/llm/mindcraft-main/src/agent/agent.js:139:23)
Purely conversational response: My brain disconnected, try again.
```

Is there any way around this or will I be forced to try and use Ollama? I'm not entirely keen on trying to set up a whole new program and potentially having to go through downloading Llama 3 again when I've already got it working via LM Studio and should just be able to use the endpoints.

**Comment by Gyramuur** [comment]
I've pushed a little further with this to see if I can find some sort of workaround. The first thing I tried was using OpenAI but with "lm-studio" as the OPENAI_API_KEY. As probably expected, this doesn't work:

```
Z:\llm\mindcraft-take2\mindcraft-main>node main.js
Using chat settings: { model: 'gpt-4o-mini', api: 'openai' }
Using embedding settings: { api: 'openai' }
file:///Z:/llm/mindcraft-take2/mindcraft-main/node_modules/openai/error.mjs:44
            return new AuthenticationError(status, error, message, headers);
                   ^

AuthenticationError: 401 Incorrect API key provided: lm-studio. You can find your API key at https://platform.openai.com/account/api-keys.
    at APIError.generate (file:///Z:/llm/mindcraft-take2/mindcraft-main/node_modules/openai/error.mjs:44:20)
    at OpenAI.makeStatusError (file:///Z:/llm/mindcraft-take2/mindcraft-main/node_modules/openai/core.mjs:268:25)
    at OpenAI.makeRequest (file:///Z:/llm/mindcraft-take2/mindcraft-main/node_modules/openai/core.mjs:311:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async GPT.embed (file:///Z:/llm/mindcraft-take2/mindcraft-main/src/models/gpt.js:51:27)
    at async file:///Z:/llm/mindcraft-take2/mindcraft-main/src/utils/examples.js:37:46
    at async Promise.all (index 2)
    at async Examples.load (file:///Z:/llm/mindcraft-take2/mindcraft-main/src/utils/examples.js:39:13)
    at async Promise.all (index 0)
    at async Prompter.initExamples (file:///Z:/llm/mindcraft-take2/mindcraft-main/src/agent/prompter.js:101:9) {
  status: 401,
  headers: {
    'alt-svc': 'h3=":443"; ma=86400',
    'cf-cache-status': 'DYNAMIC',
    'cf-ray': '8c1f29b8bf3217c8-MEL',
    connection: 'keep-alive',
    'content-length': '259',
    'content-type': 'application/json; charset=utf-8',
    date: 'Thu, 12 Sep 2024 10:20:06 GMT',
    server: 'cloudflare',
    'set-cookie': '__cf_bm=IYwkdOd5_kOQAIutDc_9vDTJcOJPT7OvOPlYIlStgMI-1726136406-1.0.1.1-TJAMiZQm9kE0NolwvBcxfBZDFq9ZutT3618s8IqFyFN4ejZnKguVvjj9P1kFouwsKcrcUIUk6jgE4cUF2.gaEg; path=/; expires=Thu, 12-Sep-24 10:50:06 GMT; domain=.api.openai.com; HttpOnly; Secure; SameSite=None, _cfuvid=xTnr_5ZUUb01XytTNaCK6JfjRIkDfpzrBsTXh9hOYag-1726136406097-0.0.1.1-604800000; path=/; domain=.api.openai.com; HttpOnly; Secure; SameSite=None',
    'strict-transport-security': 'max-age=15552000; includeSubDomains; preload',
    vary: 'Origin',
    'x-content-type-options': 'nosniff',
    'x-request-id': 'req_a987d20faece35cecfc9c47219810395'
  },
  request_id: 'req_a987d20faece35cecfc9c47219810395',
  error: {
    message: 'Incorrect API key provided: lm-studio. You can find your API key at https://platform.openai.com/account/api-keys.',
    type: 'invalid_request_error',
    param: null,
    code: 'invalid_api_key'
  },
  code: 'invalid_api_key',
  param: null,
  type: 'invalid_request_error'
}

Node.js v20.17.0
Agent process exited with code 1 and signal null
Agent process exited too quickly. Killing entire process. Goodbye.
```

So back to the drawing board, I decided to open up andy.json and try "llama3" as the model. But now I'm getting hit with a different error:

```
Z:\llm\mindcraft-take2\mindcraft-main>node main.js
Using chat settings: { model: 'llama3', api: 'ollama' }
Using embedding settings: { api: 'none' }
Unknown embedding:  none . Using word overlap.
Logging in...
Mineflayer detected that you are using a deprecated event (physicTick)! Please use this event (physicsTick) instead.
andy spawned.
selected examples:
brug: Remember that your base is here.
user43: Set a goal to survive on your own forever.
Awaiting local response... (model: llama3)
Failed to send Ollama request.
Error: Ollama Status: 400
    at Local.send (file:///Z:/llm/mindcraft-take2/mindcraft-main/src/models/local.js:52:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Local.sendRequest (file:///Z:/llm/mindcraft-take2/mindcraft-main/src/models/local.js:18:19)
    at async Prompter.promptConvo (file:///Z:/llm/mindcraft-take2/mindcraft-main/src/agent/prompter.js:165:16)
    at async Agent.handleMessage (file:///Z:/llm/mindcraft-take2/mindcraft-main/src/agent/agent.js:139:23)
file:///Z:/llm/mindcraft-take2/mindcraft-main/src/agent/commands/index.js:19
    const commandMatch = message.match(commandRegex);
                                 ^

TypeError: Cannot read properties of null (reading 'match')
    at containsCommand (file:///Z:/llm/mindcraft-take2/mindcraft-main/src/agent/commands/index.js:19:34)
    at Agent.handleMessage (file:///Z:/llm/mindcraft-take2/mindcraft-main/src/agent/agent.js:141:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v20.17.0
Agent process exited with code 1 and signal null
Agent process exited too quickly. Killing entire process. Goodbye.
```

Interestingly enough, it seems like LM Studio itself receives the request, but doesn't work because it believes the "messages" field is empty:

[2024-09-12 20:40:34.168] [INFO] Received POST request to /v1/chat/completions with body: {}
[2024-09-12 20:40:34.169] [ERROR] 'messages' field is required

Unfortunately I can't really figure out where to go next. Seems like it's actually communicating with LM Studio but can't work due to the message.match() method somehow returning an empty message field.

**Comment by Atomicxam** [comment]
Primera vez que utilizo esto, la verdad ChatGPT hizo casi todo el trabajo, pero avance es avance y creo que debo compartirlo, modifiqué varios archivos (agent-process, init-agent, agent, ANIA, main, settings) y logré que funcionara con lm-studio con algunos problemas, el bot responde a las solicitudes, pero no es capaz de recordar. Igualmente debido a problemas de hardware no pude ejecutar modelos grandes, pero los que probé (Gemma o Llama) funcionaban.


![Captura de pantalla 2024-09-15 183349](https://github.com/user-attachments/assets/d02f9ff8-511f-48f4-8f83-68d5a17f224f)
![image](https://github.com/user-attachments/assets/5e52d650-2bf7-4475-8cd5-3e4aad048035)
![image](https://github.com/user-attachments/assets/5a0941e0-f3e3-4e4a-bdcf-7361492ef8ab)
![image](https://github.com/user-attachments/assets/4b15e08c-d169-4d03-a494-af9a1e0e1387)

las imagenes no muestran las falencias de memoria, favor si alguien le puede echar un ojo al codigo, abriría muchas puertas
[TST.zip](https://github.com/user-attachments/files/17007504/TST.zip)

Saludos a quien me lea (:

**Comment by riqvip** [comment]
LM Studio is now officially supported in the latest release of mindcraft.
