### ISSUE TITLE
i need help 

### ISSUE THREAD

**Issue by witherheadhd** [kolbytn/mindcraft#184]
PS C:\Users\phili\Desktop\mindcraft-main\mindcraft-main> node main.js
Using chat settings: { model: 'llama3.1:70b', api: 'ollama' }
Using embedding settings: { api: 'none' }
Unknown embedding:  none . Using word overlap.
Logging in...
Mineflayer detected that you are using a deprecated event (physicTick)! Please use this event (physicsTick) instead.
Bob spawned.
selected examples:
brug: Remember that your base is here.
user43: Set a goal to survive on your own forever.
Awaiting local response... (model: llama3.1:70b)
Failed to send Ollama request.
Error: Ollama Status: 500
    at Local.send (file:///C:/Users/phili/Desktop/mindcraft-main/mindcraft-main/src/models/local.js:52:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Local.sendRequest (file:///C:/Users/phili/Desktop/mindcraft-main/mindcraft-main/src/models/local.js:18:19)
    at async Prompter.promptConvo (file:///C:/Users/phili/Desktop/mindcraft-main/mindcraft-main/src/agent/prompter.js:165:16)
    at async Agent.handleMessage (file:///C:/Users/phili/Desktop/mindcraft-main/mindcraft-main/src/agent/agent.js:139:23)
file:///C:/Users/phili/Desktop/mindcraft-main/mindcraft-main/src/agent/commands/index.js:19
    const commandMatch = message.match(commandRegex);
                                 ^

TypeError: Cannot read properties of null (reading 'match')
    at containsCommand (file:///C:/Users/phili/Desktop/mindcraft-main/mindcraft-main/src/agent/commands/index.js:19:34)
    at Agent.handleMessage (file:///C:/Users/phili/Desktop/mindcraft-main/mindcraft-main/src/agent/agent.js:141:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v20.17.0
Agent process exited with code 1 and signal null
Agent process exited too quickly. Killing entire process. Goodbye.
PS C:\Users\phili\Desktop\mindcraft-main\mindcraft-main> 

this happens pls help

**Comment by hirun1228** [comment]
did you download llama3.1:70b using this command? ollama pull llama3.1:70b

**Comment by uukelele** [comment]
Running `llama3.1:70b` on consumer-grade hardware isn't necessary a good idea. If you can run it, even a 27B model is good enough for mindcraft.
