### ISSUE TITLE
Crash on login - Cannot read properties of undefined (reading 'overworld')

### ISSUE THREAD

**Issue by CuriousCodingCanadian** [kolbytn/mindcraft#194]
On startup, I get the following error:
```
C:\Users\Eesa\Downloads\mindcraft-main\mindcraft-main>node main.js
Using chat settings: { model: 'gpt-4o-mini', api: 'openai' }
Using embedding settings: { api: 'openai' }
Logging in...
Mineflayer detected that you are using a deprecated event (physicTick)! Please use this event (physicsTick) instead.
C:\Users\Eesa\Downloads\mindcraft-main\mindcraft-main\node_modules\minecraft-protocol\src\transforms\framing.js:67
          } else { throw e }
                   ^

TypeError: Cannot read properties of undefined (reading 'overworld')
    at handleRespawnPacketData (C:\Users\Eesa\Downloads\mindcraft-main\mindcraft-main\node_modules\mineflayer\lib\plugins\game.js:46:63)
    at Client.<anonymous> (C:\Users\Eesa\Downloads\mindcraft-main\mindcraft-main\node_modules\mineflayer\lib\plugins\game.js:80:5)
    at Client.emit (node:events:531:35)
    at emitPacket (C:\Users\Eesa\Downloads\mindcraft-main\mindcraft-main\node_modules\minecraft-protocol\src\client.js:83:12)
    at FullPacketParser.<anonymous> (C:\Users\Eesa\Downloads\mindcraft-main\mindcraft-main\node_modules\minecraft-protocol\src\client.js:112:9)
    at FullPacketParser.emit (node:events:519:28)
    at addChunk (C:\Users\Eesa\Downloads\mindcraft-main\mindcraft-main\node_modules\protodef\node_modules\readable-stream\lib\_stream_readable.js:279:12)
    at readableAddChunk (C:\Users\Eesa\Downloads\mindcraft-main\mindcraft-main\node_modules\protodef\node_modules\readable-stream\lib\_stream_readable.js:262:11)
    at Readable.push (C:\Users\Eesa\Downloads\mindcraft-main\mindcraft-main\node_modules\protodef\node_modules\readable-stream\lib\_stream_readable.js:228:10)
    at Transform.push (C:\Users\Eesa\Downloads\mindcraft-main\mindcraft-main\node_modules\protodef\node_modules\readable-stream\lib\_stream_transform.js:132:32)

Node.js v20.17.0
Agent process exited with code 1 and signal null
Agent process exited too quickly. Killing entire process. Goodbye.
```
with settings.js
```
export default 
{
    "minecraft_version": "1.20.4", // supports up to 1.20.4
    "host": "redacted", // or "localhost", "your.ip.address.here"
    "port": 25769,
    "auth": "offline", // or "microsoft"
    
    "profiles": [
        "./andy.json",
        // add more profiles here, check ./profiles/ for more
        // more than 1 profile will require you to /msg each bot indivually
    ],
    "load_memory": false, // load memory from previous session
    "init_message": "Say hello world and your name", // sends to all on spawn

    "allow_insecure_coding": true, // allows newAction command and model can write/run code on your computer. enable at own risk
    "code_timeout_mins": 10, // minutes code is allowed to run. -1 for no timeout
    
    "max_commands": -1, // max number of commands to use in a response. -1 for no limit
    "verbose_commands": true, // show full command syntax
    "narrate_behavior": true, // chat simple automatic actions ('Picking up item!')
}
```

It is worth mentioning that the server runs viabackwards.

**Comment by CuriousCodingCanadian** [comment]
Source code of the mod is available on request.

**Comment by CuriousCodingCanadian** [comment]
Using the same config as the bot on a real client - offline login, 1.20.4, and connecting to the server with ViaBackwards works without issue.

**Comment by luigi052005** [comment]
I have the same issue

**Comment by uukelele** [comment]
Use the latest version of mindcraft and node.js v22 (LTS), as it should be able to fix this issue.

If your problem persists, please feel free to reopen this issue.
