### ISSUE TITLE
Andy joins then restarts immediately after

### ISSUE THREAD

**Issue by ft7utrt7yguhy7t6f7ygvh** [kolbytn/mindcraft#207]
I start the bot, he joins then 5 seconds later leaves and restarts.
it says,
TypeError: Cannot read properties of null (reading 'match')
    at containsCommand (file:///C:/Users/####/Downloads/mindcraft-main/mindcraft-main/src/agent/commands/index.js:19:34)
    at Agent.handleMessage (file:///C:/Users/####/Downloads/mindcraft-main/mindcraft-main/src/agent/agent.js:151:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.18.0
Agent process exited with code 1 and signal null
Restarting agent...

**Comment by Entropy159** [comment]
I have this same issue, but it crashes immediately when joining.

**Comment by Entropy159** [comment]
I fixed this for me by correcting the model name. In my case it was llama3 when it should've been llama3.2

**Comment by ft7utrt7yguhy7t6f7ygvh** [comment]
> I fixed this for me by correcting the model name. In my case it was llama3 when it should've been llama3.2

I'll try this and see if it works, thanks for telling me how you fixed it though
