### ISSUE TITLE
an error comes when starting

### ISSUE THREAD

**Issue by robogamer9849** [kolbytn/mindcraft#210]
this shows up when running node main.js 

`node:fs:448
    return binding.readFileUtf8(path, stringToFlags(options.flag));
                   ^

Error: ENOENT: no such file or directory, open './gemmma.json'
    at readFileSync (node:fs:448:20)
    at new Prompter (file:///home/taha/Documents/games/mindcraft/src/agent/prompter.js:18:35)
    at Agent.start (file:///home/taha/Documents/games/mindcraft/src/agent/agent.js:15:25)
    at file:///home/taha/Documents/games/mindcraft/src/process/init-agent.js:27:13
    at ModuleJob.run (node:internal/modules/esm/module_job:234:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:473:24)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:123:5) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: './gemmma.json'
}

Node.js v20.17.0
Agent process exited with code 1 and signal null
Agent process exited too quickly. Killing entire process. Goodbye.`

**Comment by uukelele** [comment]
You need to specify your API keys in `keys.json`, and set the model to the one you want to use.
