### ISSUE TITLE
Syntax error on running "node main.js"

### ISSUE THREAD

**Issue by plyrnoob2890** [kolbytn/mindcraft#233]
hello. i am using Ollama with this but when I use node main.js it just throws this syntax error:

SyntaxError: Expected ',' or '}' after property value in JSON at position 49
    at JSON.parse (<anonymous>)
    at new Prompter (file:///D:/Chrome%20Downloads/mindcraft-main/mindcraft-main/src/agent/prompter.js:19:29)
    at Agent.start (file:///D:/Chrome%20Downloads/mindcraft-main/mindcraft-main/src/agent/agent.js:16:25)
    at file:///D:/Chrome%20Downloads/mindcraft-main/mindcraft-main/src/process/init-agent.js:33:13
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async loadESM (node:internal/process/esm_loader:28:7)
    at async handleMainPromise (node:internal/modules/run_main:113:12)

**Comment by uukelele** [comment]
You have a syntax error in your JSON file.

Use a JSON linter to find the issue, or you could paste it into ChatGPT and ask for guidance.

Alternatively, re-use the original `andy.json` file from the repo.
