### ISSUE TITLE
Micrsoft Authentication Error

### ISSUE THREAD

**Issue by ItsChugg** [kolbytn/mindcraft#237]
I'm getting an error when trying to authenticate with a Microsoft account. After supposedly logging in successfully I'm getting this output on my console on loop until I close it.
```
Error: Failed to acquire authorization code from device token (invalid_grant) - The provided value for the input parameter 'device_code' has already been used.
    at C:\Users\russe\Desktop\mindcraft-main\node_modules\prismarine-auth\src\TokenManagers\LiveTokenManager.js:137:23
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async LiveTokenManager.authDeviceCode (C:\Users\russe\Desktop\mindcraft-main\node_modules\prismarine-auth\src\TokenManagers\LiveTokenManager.js:131:23)
    at async MicrosoftAuthFlow.getMsaToken (C:\Users\russe\Desktop\mindcraft-main\node_modules\prismarine-auth\src\MicrosoftAuthFlow.js:99:19)
    at async retry.msa.forceRefresh (C:\Users\russe\Desktop\mindcraft-main\node_modules\prismarine-auth\src\MicrosoftAuthFlow.js:135:24)
    at async retry (C:\Users\russe\Desktop\mindcraft-main\node_modules\prismarine-auth\src\MicrosoftAuthFlow.js:20:20)
    at async MicrosoftAuthFlow.getXboxToken (C:\Users\russe\Desktop\mindcraft-main\node_modules\prismarine-auth\src\MicrosoftAuthFlow.js:134:12)
    at async retry.xbl.forceRefresh (C:\Users\russe\Desktop\mindcraft-main\node_modules\prismarine-auth\src\MicrosoftAuthFlow.js:163:22)
    at async retry (C:\Users\russe\Desktop\mindcraft-main\node_modules\prismarine-auth\src\MicrosoftAuthFlow.js:20:20)
    at async MicrosoftAuthFlow.getMinecraftJavaToken (C:\Users\russe\Desktop\mindcraft-main\node_modules\prismarine-auth\src\MicrosoftAuthFlow.js:162:7)
```

**Comment by uukelele** [comment]
Maybe try using a newer version of mindcraft & update its dependencies, as this may have fixed the error.

If your problem persists, please feel free to reopen this issue.
