### ISSUE TITLE
node:internal/modules/cjs/loader:1228   throw err;   ^

### ISSUE THREAD

**Issue by realjoschi64xd** [kolbytn/mindcraft#243]
Error: Cannot find module 'C:\Users\eplan\src\process\init-agent.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
    at Module._load (node:internal/modules/cjs/loader:1051:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v20.18.0
Agent process exited with code 1 and signal null
Agent process ./andy.json exited too quickly and will not be restarted.
All agent processes have ended. Exiting.

**Comment by realjoschi64xd** [comment]
[ './andy.json' ]
Using chat settings: { model: 'gpt-4o-mini', api: 'openai' }
Using embedding settings: { api: 'openai' }
Error with embedding model, using word overlap instead.
Error with embedding model, using word overlap instead.
Logging in...
C:\Users\eplan\Downloads\mindcraft-main\mindcraft-main\node_modules\mineflayer\lib\loader.js:108
    const version = require('minecraft-data')(bot._client.version).version
                                                                  ^

TypeError: Cannot read properties of null (reading 'version')
    at next (C:\Users\eplan\Downloads\mindcraft-main\mindcraft-main\node_modules\mineflayer\lib\loader.js:108:67)
    at createBot (C:\Users\eplan\Downloads\mindcraft-main\mindcraft-main\node_modules\mineflayer\lib\loader.js:105:34)
    at initBot (file:///C:/Users/eplan/Downloads/mindcraft-main/mindcraft-main/src/utils/mcdata.js:57:15)
    at Agent.start (file:///C:/Users/eplan/Downloads/mindcraft-main/mindcraft-main/src/agent/agent.js:27:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v20.18.0
Agent process exited with code 1 and signal null
Agent process ./andy.json exited too quickly and will not be restarted.
All agent processes have ended. Exiting.

**Comment by Lawtro37** [comment]
same issue here, will update you if I fix it 👍

**Comment by Lawtro37** [comment]
ok I fixed it you need to use the command "npm run postinstall" to apply the patches to mineflayer

**Comment by uukelele** [comment]
Use the latest version of mindcraft and node.js v22 (LTS), as it should be able to fix this issue.

If your problem persists, please feel free to reopen this issue.
