### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'match')\n

### ISSUE THREAD

**Issue by Variacat** [kolbytn/mindcraft#319]
[ './andy.json' ]
Starting agent with profile: ./andy.json
Starting agent initialization with profile: ./andy.json
Initializing action manager...
Initializing prompter...
Using chat settings: { model: 'llama3.2', api: 'ollama' }
Using embedding settings: { api: 'none' }
Unknown embedding:  none . Using word overlap.
Initializing history...
Initializing coder...
Initializing npc controller...
Initializing memory bank...
Initializing self prompter...
Initializing examples...
Logging into minecraft...
(node:8116) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Logged in!
andy spawned.
received message from system : Say hello world and your name
Saved memory to: ./bots/andy/memory.json
selected examples:
brug: Remember that your base is here.
user43: Set a goal to survive on your own forever.
Awaiting local response... (model: llama3.2)
Failed to send Ollama request.
{}
Error handling startup conditions: {}
Unhandled Rejection at: {
  promise: Object [Promise] {},
  reason: {},
  stack: "TypeError: Cannot read properties of null (reading 'match')\n" +
    '  at containsCommand (file:///C:/Users/Variacat/Documents/mindcraft-main/src/agent/commands/index.js:21:34)\n' +
    '  at Agent.handleMessage (file:///C:/Users/Variacat/Documents/mindcraft-main/src/agent/agent.js:269:32)\n' +
    '  at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n' +
    '  at async Agent._handleStartupConditions (file:///C:/Users/Variacat/Documents/mindcraft-main/src/agent/agent.js:164:17)'
}
SES_UNHANDLED_REJECTION: {}
Agent process exited with code 1 and signal null
Agent process ./andy.json exited too quickly and will not be restarted.
All agent processes have ended. Exiting.

**Comment by Uncover-F** [comment]
This seems to be a code issue and probablly has nothing to do with you. What OS are u on? It’s not so stable on Linux or Mac.

**Comment by Koolz702** [comment]
Same issue here on Win11

**Comment by Harry989** [comment]
> This seems to be a code issue and probablly has nothing to do with you. What OS are u on? It’s not so stable on Linux or Mac.

I have this exact error, I am currently on Windows 10.

**Comment by Tascok** [comment]
> This seems to be a code issue and probablly has nothing to do with you. What OS are u on? It’s not so stable on Linux or Mac.

I have this exact error, I am currently on Windows 11

**Comment by uukelele** [comment]
Update to the latest version of mindcraft.

If your problem persists, please feel free to reopen this issue.
