### ISSUE TITLE
the bots join and then instantly leave

### ISSUE THREAD

**Issue by macintoshidiot** [kolbytn/mindcraft#354]
Agent process exited with code 1 and signal null
Agent process ./andy.json exited too quickly and will not be restarted.
Error handling startup conditions: {}
Unhandled Rejection at: {
  promise: Object [Promise] {},
  reason: {},
  stack: "TypeError: Cannot read properties of undefined (reading 'name')\n" +
    '  at Module.getBiomeName (file:///E:/mindcraft-main2/src/agent/library/world.js:310:38)\n' +
    '  at Object.perform (file:///E:/mindcraft-main2/src/agent/commands/queries.js:23:40)\n' +
    '  at Prompter.replaceStrings (file:///E:/mindcraft-main2/src/agent/prompter.js:165:52)\n' +
    '  at Prompter.promptConvo (file:///E:/mindcraft-main2/src/agent/prompter.js:227:29)\n' +
    '  at async Agent.handleMessage (file:///E:/mindcraft-main2/src/agent/agent.js:273:23)\n' +
    '  at async Agent._handleStartupConditions (file:///E:/mindcraft-main2/src/agent/agent.js:170:17)'
}
SES_UNHANDLED_REJECTION: {}
Agent process exited with code 1 and signal null

**Comment by uukelele** [comment]
Use the latest version of mindcraft, as it should be able to fix this issue.

If your problem persists, please feel free to reopen this issue.
