### ISSUE TITLE
RateLimitError: 429, cannot run main.js

### ISSUE THREAD

**Issue by Luca-Girotti** [kolbytn/mindcraft#49]
Hello,

Whenever I am trying to run "node main.js" I get the following error:

Loading examples...
file:///Users/iluca/Documents/Leiden%20Univ/Master/Games%20AI/Assignment%203/mindcraft/node_modules/openai/error.mjs:59
            return new RateLimitError(status, error, message, headers);
                   ^

RateLimitError: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.
    at APIError.generate (file:///Users/iluca/Documents/Leiden%20Univ/Master/Games%20AI/Assignment%203/mindcraft/node_modules/openai/error.mjs:59:20)
    at OpenAI.makeStatusError (file:///Users/iluca/Documents/Leiden%20Univ/Master/Games%20AI/Assignment%203/mindcraft/node_modules/openai/core.mjs:256:25)
    at OpenAI.makeRequest (file:///Users/iluca/Documents/Leiden%20Univ/Master/Games%20AI/Assignment%203/mindcraft/node_modules/openai/core.mjs:299:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async GPT.embed (file:///Users/iluca/Documents/Leiden%20Univ/Master/Games%20AI/Assignment%203/mindcraft/src/models/gpt.js:56:27)
    at async file:///Users/iluca/Documents/Leiden%20Univ/Master/Games%20AI/Assignment%203/mindcraft/src/utils/examples.js:20:31
    at async Promise.all (index 5)
    at async Examples.load (file:///Users/iluca/Documents/Leiden%20Univ/Master/Games%20AI/Assignment%203/mindcraft/src/utils/examples.js:23:25)
    at async Prompter.initExamples (file:///Users/iluca/Documents/Leiden%20Univ/Master/Games%20AI/Assignment%203/mindcraft/src/agent/prompter.js:44:9)
    at async Agent.start (file:///Users/iluca/Documents/Leiden%20Univ/Master/Games%20AI/Assignment%203/mindcraft/src/agent/agent.js:15:9) {
  status: 429,
  headers: {
    'alt-svc': 'h3=":443"; ma=86400',
    'cf-cache-status': 'DYNAMIC',
    'cf-ray': '875c95ac888a970d-AMS',
    connection: 'keep-alive',
    'content-length': '337',
    'content-type': 'application/json; charset=utf-8',
    date: 'Wed, 17 Apr 2024 12:58:06 GMT',
    server: 'cloudflare',
    'set-cookie': '__cf_bm=5smTpOKE2NHa2D_1BAOenwmYG2oJ2Xt3KR1Q7Eixqeo-1713358686-1.0.1.1-NeSwO9K.H2l.uO3xrSS53kmWK9Hhp81qc_eyroOcJ04Bl.U_HgELA9fQgrFEGq7JMH6wxE.o7VVJ4Nw.tE8j_g; path=/; expires=Wed, 17-Apr-24 13:28:06 GMT; domain=.api.openai.com; HttpOnly; Secure; SameSite=None, _cfuvid=XxvlQAw4wGsfsEiI7hpBtXi9qpDNxJCBSWKk443MZW4-1713358686295-0.0.1.1-604800000; path=/; domain=.api.openai.com; HttpOnly; Secure; SameSite=None',
    'strict-transport-security': 'max-age=15724800; includeSubDomains',
    vary: 'Origin',
    'x-request-id': 'req_f74558cd10c5b7f498219040d82a022f'
  },
  request_id: 'req_f74558cd10c5b7f498219040d82a022f',
  error: {
    message: 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.',
    type: 'insufficient_quota',
    param: null,
    code: 'insufficient_quota'
  },
  code: 'insufficient_quota',
  param: null,
  type: 'insufficient_quota'
}

Node.js v18.17.1
Agent process exited with code 1 and signal null
Agent process exited too quickly. Killing entire process. Goodbye.

Any ideas how to perhaps fix this?

**Comment by kolbytn** [comment]
You probably need to add money to your OpenAI account. See [this issue](https://github.com/kolbytn/mindcraft/issues/31).
