### ISSUE TITLE
can't open, problem with mineflayer and version 'const'

### ISSUE THREAD

**Issue by viibri** [kolbytn/mindcraft#54]
```
C:\Users\won'tshowmypc'suser\mindcraft\node_modules\mineflayer\lib\loader.js:108
    const version = require('minecraft-data')(bot._client.version).version
                                                                  ^

TypeError: Cannot read properties of null (reading 'version')
    at next (C:\Users\won'tshowmypc'suser\mindcraft\node_modules\mineflayer\lib\loader.js:108:67)
    at createBot (C:\Users\won'tshowmypc'suser\mindcraft\node_modules\mineflayer\lib\loader.js:105:34)
    at initBot (file:///C:/Users/won'tshowmypc'suser/mindcraft/src/utils/mcdata.js:51:15)
    at Agent.start (file:///C:/Users/won'tshowmypc'suser/mindcraft/src/agent/agent.js:24:20)

Node.js v18.16.0
Agent process exited with code 1 and signal null
Agent process exited too quickly. Killing entire process. Goodbye.
```

i've done all the readme says, this happens
i'm using only a claude api key

**Comment by IceTank** [comment]
This is most likely because you are using a version that is not supported by the minecraft-data module. 1.20.1 should be supported but I think 1.20.4 is not. If you are already using an 1.20.1 try doing `npm update` to update installed modules.

**Comment by kolbytn** [comment]
1.20.4 should also be supported, but I don't think any higher than that is.
