### ISSUE TITLE
Fail to add bot

### ISSUE THREAD

**Issue by JJmikey** [kolbytn/mindcraft#61]
I followed the installation and local run guideline but I can't get it works.
I did the installation and run the command below, then nothing happens and no agent shows up when I go back to game.
Could anyone suggest a solution? thanks！

~/mindcraft$ node main.js
Loading examples...
Examples loaded.
Logging in...
Mineflayer detected that you are using a deprecated event (physicTick)! Please use this event (physicsTick) instead.
Agent process exited with code 0 and signal null

**Comment by kolbytn** [comment]
Did you make the game open to LAN on port 55916?

**Comment by kolbytn** [comment]
Can you describe the rest of your setup and install steps?

**Comment by jkramer5103** [comment]
Now I also have this Issue

**Comment by JJmikey** [comment]
> Can you describe the rest of your setup and install steps?

At first I set up in Ubuntu. I added GEMINI_API_KEY as environment variables,downloaded the repository and run npm install.  Then I changed  "model" to "gemini-1.5-pro-latest" in andy.json.
But since I failed to add bot, i switched to Windows and did the above again.
This time, log is like:
Using chat settings: { model: 'gemini-1.5-pro-latest', api: 'google' }
Using embedding settings: { api: 'google' }
Loading examples...
file:///C:/Users/cydec/Documents/mindcraft-main/src/models/gemini.js:50
            model = this.genAI.getGenerativeModel(
                  ^

ReferenceError: model is not defined
    at Gemini.embed (file:///C:/Users/cydec/Documents/mindcraft-main/src/models/gemini.js:50:19)
    at Examples.load (file:///C:/Users/cydec/Documents/mindcraft-main/src/utils/examples.js:37:63)
    at Prompter.initExamples (file:///C:/Users/cydec/Documents/mindcraft-main/src/agent/prompter.js:83:35)
    at Agent.start (file:///C:/Users/cydec/Documents/mindcraft-main/src/agent/agent.js:20:29)
    at file:///C:/Users/cydec/Documents/mindcraft-main/src/process/init-agent.js:27:13
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)
    at async loadESM (node:internal/process/esm_loader:28:7)
    at async handleMainPromise (node:internal/modules/run_main:113:12)

Node.js v20.12.2
Agent process exited with code 1 and signal null
Restarting agent...
Using chat settings: { model: 'gemini-1.5-pro-latest', api: 'google' }
Using embedding settings: { api: 'google' }
Loading examples...
file:///C:/Users/cydec/Documents/mindcraft-main/src/models/gemini.js:50
            model = this.genAI.getGenerativeModel(
                  ^

ReferenceError: model is not defined
    at Gemini.embed (file:///C:/Users/cydec/Documents/mindcraft-main/src/models/gemini.js:50:19)
    at Examples.load (file:///C:/Users/cydec/Documents/mindcraft-main/src/utils/examples.js:37:63)
    at Prompter.initExamples (file:///C:/Users/cydec/Documents/mindcraft-main/src/agent/prompter.js:83:35)
    at Agent.start (file:///C:/Users/cydec/Documents/mindcraft-main/src/agent/agent.js:20:29)
    at file:///C:/Users/cydec/Documents/mindcraft-main/src/process/init-agent.js:27:13
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)
    at async loadESM (node:internal/process/esm_loader:28:7)
    at async handleMainPromise (node:internal/modules/run_main:113:12)

Node.js v20.12.2
Agent process exited with code 1 and signal null
Agent process exited too quickly. Killing entire process. Goodbye.
-----
so I was thinking if that's a problem with Gemini, and I switched to OpenAI API key using gpt-3.5-turbo as per default in andy.json.
The log is like:
Using chat settings: { model: 'gpt-3.5-turbo', api: 'openai' }
Using embedding settings: { api: 'openai' }
Loading examples...
Examples loaded.
Logging in...
Mineflayer detected that you are using a deprecated event (physicTick)! Please use this event (physicsTick) instead.
Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20) {
  errno: -4077,
  code: 'ECONNRESET',
  syscall: 'read'
}
Agent process exited with code 0 and signal null
----
but then again when I went back to game, no agent shown up :(

**Comment by kolbytn** [comment]
I believe this pending PR should resolve the issue. Let me know if it does not.
https://github.com/kolbytn/mindcraft/pull/82

**Comment by JJmikey** [comment]
Thanks for the update. Just tried and still have errors:

node:internal/modules/esm/resolve:854
  throw new ERR_MODULE_NOT_FOUND(packageName, fileURLToPath(base), null);
        ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'yargs' imported from C:\Users\XXX\Documents\mindcraft\src\process\init-agent.js
    at packageResolve (node:internal/modules/esm/resolve:854:9)
    at moduleResolve (node:internal/modules/esm/resolve:927:18)
    at defaultResolve (node:internal/modules/esm/resolve:1157:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:390:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:359:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:234:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:87:39)
    at link (node:internal/modules/esm/module_job:86:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

Node.js v20.12.2
Agent process exited with code 1 and signal null
Agent process exited too quickly. Killing entire process. Goodbye.

**Comment by kolbytn** [comment]
You may need to rerun `npm install` after pulling from main?
